In [1]:
import numpy as np
s = np.array([1,1,1,-1]).reshape((4,1))
w = s @ s.T - 1* np.eye(4)
def IAAN(w,s):
    stop = False
    it = 0
    while not stop:
        it += 1
        y = np.sign(s.T @ w).reshape(4,1)
        if (y == s).all() or it == 100:
            stop = True
            return y, it
        s = y 
print(w)


array([[ 0.,  1.,  1., -1.],
       [ 1.,  0.,  1., -1.],
       [ 1.,  1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [0]:
m1 = np.array([1,0,0,0]).reshape((4,1))
m2 = np.array([0,1,0,0]).reshape((4,1))
m3 = np.array([0,0,1,0]).reshape((4,1))
m4 = np.array([0,0,0,-1]).reshape((4,1))

n1 = np.array([1,-1,-1,1]).reshape((4,1))
n2 = np.array([-1,1,-1,1]).reshape((4,1))
n3 = np.array([-1,-1,1,1]).reshape((4,1))
n4 = np.array([-1,-1,-1,-1]).reshape((4,1))

# Iterative AAN

In [3]:
print(s.T,IAAN(w,s)[0].T)
print(n1.T,IAAN(w,n1)[0].T)
print(n2.T,IAAN(w,n2)[0].T)
print(n3.T,IAAN(w,n3)[0].T)
print(n4.T,IAAN(w,n4)[0].T)
print(m1.T,IAAN(w,m1)[0].T)
print(m2.T,IAAN(w,m2)[0].T)
print(m3.T,IAAN(w,m3)[0].T)
print(m4.T,IAAN(w,m4)[0].T)


[[ 1  1  1 -1]] [[ 1.  1.  1. -1.]]
[[ 1 -1 -1  1]] [[-1. -1. -1.  1.]]
[[-1  1 -1  1]] [[-1. -1. -1.  1.]]
[[-1 -1  1  1]] [[-1. -1. -1.  1.]]
[[-1 -1 -1 -1]] [[-1. -1. -1.  1.]]
[[1 0 0 0]] [[ 1.  1.  1. -1.]]
[[0 1 0 0]] [[ 1.  1.  1. -1.]]
[[0 0 1 0]] [[ 1.  1.  1. -1.]]
[[ 0  0  0 -1]] [[ 1.  1.  1. -1.]]


# Discrete net


In [0]:
def DHN(w,x):
    stop = False
    y = x
    while True:
        ind = np.array([0,1,2,3])
        np.random.shuffle(ind)
        for i in ind:
            y_in = x[i] + y.T @ w[i]
            y[i] = np.sign(y_in)
        if (y == x).all():
            return y
        x = y

In [5]:

print(DHN(w,s).T)
print(DHN(w,n1).T)
print(DHN(w,n2).T)
print(DHN(w,n3).T)
print(DHN(w,n4).T)
print(DHN(w,m1).T)
print(DHN(w,m2).T)
print(DHN(w,m3).T)
print(DHN(w,m4).T)


[[ 1  1  1 -1]]
[[-1 -1 -1  1]]
[[-1 -1 -1  1]]
[[-1 -1 -1  1]]
[[-1 -1 -1  1]]
[[ 1  1  1 -1]]
[[ 1  1  1 -1]]
[[ 1  1  1 -1]]
[[ 1  1  1 -1]]
